# Generated by Django 3.0.8 on 2020-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('ON', 'Toronto'), ('ON', 'Missisauga'), ('ON', 'Milton'), ('ON', 'Brampton')], max_length=21)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('USA', 'United State of America'), ('EU', 'Europe')], max_length=33)),
                ('phone', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=43)),
                ('last', models.CharField(max_length=31)),
                ('email', models.CharField(max_length=31)),
                ('address', models.ManyToManyField(blank=True, to='registration.address')),
            ],
        ),
    ]
