# Generated by Django 3.0.8 on 2020-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, choices=[('ON', 'Toronto'), ('ON', 'Missisauga'), ('ON', 'Milton'), ('ON', 'Brampton')], max_length=21),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada'), ('USA', 'United State of America'), ('EU', 'Europe')], max_length=33),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='dress',
            field=models.ManyToManyField(to='registration.dress'),
        ),
    ]
